function [a, b] = fit_Airfoil_spline(Original_X_Top, Original_Y_Top, Original_X_Bottom, Original_Y_Bottom)
%CREATEFIT(ORIGINAL_X_TOP,ORIGINAL_Y_TOP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Original_X_Top
%      Y Output: Original_Y_Top
%  Output:
%      airfoil_Top_Equation : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Apr-2020 11:32:07


%% Fit: 'Upper Airfoil'.
[xData, yData] = prepareCurveData( Original_X_Top, Original_Y_Top );

% Set up fittype and options.
ft = fittype( 'a*real(sqrt(x)) + b*x^2 + c*x^3 + d*x^4 + e*x^5 + f*real(x^(1/3))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.188955015032545 0.686775433365315 0.18351115573727 0.368484596490336 0.62561856072969 0.780227435151377];

% Fit model to data.
[airfoil_Top_Equation, gof] = fit( xData, yData, ft, opts );
a = airfoil_Top_Equation;
% Plot fit with data.
%f1 = figure;
%figure( 'Name', 'untitled fit 1' );
x_for_Plotting = 0:.0001:1;
% h = plot( x_for_Plotting, airfoil_Top_Equation(x_for_Plotting));
% %legend( h, 'Original_Y_Top vs. Original_X_Top', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'Original_X_Top' );
% ylabel( 'Original_Y_Top' );
% grid on
% axis([-.1 1.1 -.6 .6])

%--------------------------------------------%
error = abs(Original_Y_Top - airfoil_Top_Equation(Original_X_Top));
average_Error = mean(error);
max_Error = max(error);
%%disp(['---------Top curve Equation-------------'])
%%disp(['average_Error = ', num2str(average_Error)])
%%disp(['max_Error = ' num2str(max_Error)])
% f2 = figure;
% plot(Original_X_Top, error,'o')
%% Fit: 'Lower Airfoil'.
[xData, yData] = prepareCurveData( Original_X_Bottom, Original_Y_Bottom );

% Set up fittype and options.
ft = fittype( 'a*sqrt(x) + b*x^2 + c*x^3 + d*x^4 + e*x^5 + f*x^(1/3)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.188955015032545 0.686775433365315 0.18351115573727 0.368484596490336 0.62561856072969 0.780227435151377];

% Fit model to data.
[airfoil_Bottom_Equation, gof] = fit( xData, yData, ft, opts );
b = airfoil_Bottom_Equation;
% Plot fit with data.
% figure(f1);
% hold on;
% h = plot( x_for_Plotting, airfoil_Bottom_Equation(x_for_Plotting));
% %legend( h, 'Original_Y_Top vs. Original_X_Top', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% %xlabel( 'Original_X_Top' );
% %ylabel( 'Original_Y_Top' );
% grid on
% axis([-.1 1.1 -.6 .6])
% hold off;
%--------------------------------------------%
% error = abs(Original_Y_Bottom - airfoil_Bottom_Equation(Original_X_Bottom));
% average_Error = mean(error);
% max_Error = max(error);
% disp(['---------Bottom curve Equation-------------'])
% disp(['average_Error = ' num2str(average_Error)])
% disp(['max_Error = ' num2str(max_Error)])
% disp(['-------------------------------------------'])
% figure(f2);
% hold on;
% plot(Original_X_Bottom, error,'ro')
% figure(f1);
end
